const String defaultEmptyImg =
    "https://res.cloudinary.com/dhc0siki5/image/upload/v1710070251/nuncare/person_i8vdce.jpg";

const List<String> defaultSpecialities = [
  "Anesthésiologie",
  "Cardiologie",
  "Dermatologie",
  "Endocrinologie",
  "Gastro-entérologie",
  "Génétique médicale",
  "Gériatrie",
  "Hématologie",
  "Immunologie clinique et allergie",
  "Médecine interne",
  "Médecine d'urgence",
  "Néphrologie",
  "Neurologie",
  "Oncologie médicale",
  "Pédiatrie",
  "Physiatrie",
  "Pneumologie",
  "Psychiatrie",
  "Rhumatologie",
  "Médecine nucléaire",
  "Radiologie diagnostique",
  "Radio-oncologie",
  "Anatomopathologie",
  "Biochimie médicale",
  "Microbiologie et infectiologie",
  "Chirurgie",
  "Chirurgie générale",
  "Chirurgie orthopédique",
  "Chirurgie plastique",
  "Neurochirurgie",
  "Obstétrique-gynécologie",
  "Ophtalmologie",
  "Oto-rhino-laryngologie",
  "Urologie",
  "Inconnue"
];

const List<String> defaultRegions = [
  "Abidjan",
  "Yamoussoukro",
  "Lacs",
  "Iffou",
  "Bélier",
  "Moronou",
  "Comoé	",
  "Sud-Comoé	",
  "Denguélé",
  "Kabadougou",
  "Gôh-Djiboua",
  "Lôh-Djiboua ",
  "Lagunes",
  "Mé	",
  "Grands-Ponts",
  "Montagnes",
  "Cavally	",
  "Guémon",
  "Sassandra-Marahoué",
  "Marahoué",
  "Savanes",
  "Tchologo",
  "Bagoué",
  "Bas-Sassandra	",
  "San-Pédro",
  "Gbôklé",
  "Vallée du Bandama",
  "Gbêkê ",
  "Woroba",
  "Bafing",
  "Worodougou",
  "Zanzan",
  "Inconnue"
];
