const String defaultEmptyImg =
    "https://res.cloudinary.com/dhc0siki5/image/upload/v1710070251/nuncare/person_i8vdce.jpg";

const List<String> defaultSpecialities = [
  "anesthésiologie",
  "cardiologie   ",
  "dermatologie",
  "endocrinologie ",
  "gastro-entérologie ",
  "génétique médicale ",
  "gériatrie",
  "hématologie",
  "immunologie clinique et allergie",
  "médecine interne",
  "médecine d'urgence",
  "néphrologie",
  "neurologie",
  "oncologie médicale",
  "pédiatrie",
  "physiatrie",
  "pneumologie",
  "psychiatrie",
  "rhumatologie",
  "médecine nucléaire",
  "radiologie diagnostique",
  "radio-oncologie",
  "anatomopathologie",
  "biochimie médicale",
  "microbiologie et infectiologie",
  "chirurgie",
  "chirurgie générale",
  "chirurgie orthopédique",
  "chirurgie plastique",
  "neurochirurgie",
  "obstétrique-gynécologie",
  "ophtalmologie",
  "oto-rhino-laryngologie",
  "urologie",
];

const List<String> defaultRegions = [
  "Abidjan",
  "Yamoussoukro",
  "Lacs",
  "Iffou",
  "Bélier",
  "Moronou",
  "Comoé	",
  "Sud-Comoé	",
  "Denguélé",
  "Kabadougou",
  "Gôh-Djiboua",
  "Lôh-Djiboua ",
  "Lagunes",
  "Mé	",
  "Grands-Ponts",
  "Montagnes",
  "Cavally	",
  "Guémon",
  "Sassandra-Marahoué",
  "Marahoué",
  "Savanes",
  "Tchologo",
  "Bagoué",
  "Bas-Sassandra	",
  "San-Pédro",
  "Gbôklé",
  "Vallée du Bandama",
  "Gbêkê ",
  "Woroba",
  "Bafing",
  "Worodougou",
  "Zanzan",
];
